# --- LANGUAGE TOGGLE (EN / IT) ---
if "lang" not in st.session_state:
    st.session_state.lang = "EN"

lang = st.sidebar.toggle("🇮🇹 Italiano / 🇬🇧 English", value=(st.session_state.lang == "IT"))
st.session_state.lang = "IT" if lang else "EN"
L = st.session_state.lang

# Simple i18n dictionary
I18N = {
    "EN": {
        "cc_title": "Omikron Control Center",
        "cc_caption": "v20.6 Platinum Build | 2026",
        "min_vtg": "Minimum VTG Threshold",
        "min_vtg_help": "VTG (Vitality Gene Score): Intensity of the detected biological signal. Higher values mean the hub is 'active'.",
        "tmi_limit": "TMI Toxicity Limit",
        "tmi_help": "TMI (Toxicity Management Index): Toxicological risk threshold. Filters out potentially harmful targets.",
        "search_hub": "🔍 Search Hub Target",
        "search_placeholder": "e.g. KRAS",
        "k_neighbors": "Number of Neighbors (K)",
        "k_help": "Number of neighboring partners to display around the selected hub.",
        "ruo_title": "⚠️ RUO STATUS",
        "ruo_body": "Research Use Only (RUO). Data does not constitute medical or clinical advice.",
        "main_title": "🛡️ MAESTRO: Omikron Orchestra Suite",
        "axon_empty": "AXON database empty or unavailable.",
        "axon_err": "Error loading AXON:",
        "no_hub": "No hub found for:",
        "opera_director": "🎼 Opera Director:",
        "bio_desc": "**🧬 Biological Description L0:**",
        "neighbors_title": "### 🔗 First Neighbors (Hub Context)",
        "neighbors_none": "No neighbors found with current filters. Try lowering VTG or increasing TMI.",
        "export_btn": "📥 Export Full Intelligence (.txt)",
        "net_map": "🕸️ Network Interaction Map",
        "ranking": "📊 Hub Signal Ranking",
        "desk": "📂 Hub Intelligence Desk:",
        "therap": "### 💊 Therapeutics",
        "trials": "### 🧪 Clinical Trials",
        "paths": "### 🧬 Pathways",
        "no_odi": "No ODI items found.",
        "no_gci": "No GCI trials found.",
        "no_pmi": "No PMI pathways found.",
        "repo": "📚 MAESTRO Intelligence Repository",
        "disc_title": "⚠️ SCIENTIFIC AND LEGAL DISCLAIMER",
        "disc_body": "<b>MAESTRO Omikron Suite</b> is intended exclusively for Research Use Only (RUO). Generated analyses do not replace medical advice. Data reflects the current state of Omikron databases.",
        "footer": "MAESTRO v20.6 | © 2026 Omikron Orchestra Project | Powered by AXON Intelligence",
        "detected": "DETECTED",
        "linked": "Linked",
        "items": "Items",
        "details_na": "Details not available.",
    },
    "IT": {
        "cc_title": "Centro di Controllo Omikron",
        "cc_caption": "v20.6 Platinum Build | 2026",
        "min_vtg": "Soglia minima VTG",
        "min_vtg_help": "VTG (Vitality Gene Score): intensità del segnale biologico rilevato. Valori più alti indicano un hub più 'attivo'.",
        "tmi_limit": "Limite Tossicità TMI",
        "tmi_help": "TMI (Toxicity Management Index): soglia di rischio tossicologico. Filtra target potenzialmente rischiosi.",
        "search_hub": "🔍 Cerca Hub Target",
        "search_placeholder": "es. KRAS",
        "k_neighbors": "Numero di Vicini (K)",
        "k_help": "Numero di partner vicini da visualizzare attorno all'hub selezionato.",
        "ruo_title": "⚠️ SOLO PER RICERCA (RUO)",
        "ruo_body": "Solo per uso di ricerca (RUO). I dati non costituiscono consulenza medica o clinica.",
        "main_title": "🛡️ MAESTRO: Omikron Orchestra Suite",
        "axon_empty": "Database AXON vuoto o non disponibile.",
        "axon_err": "Errore nel caricamento di AXON:",
        "no_hub": "Nessun hub trovato per:",
        "opera_director": "🎼 Direttore d’Opera:",
        "bio_desc": "**🧬 Descrizione biologica L0:**",
        "neighbors_title": "### 🔗 Primi Vicini (Contesto Hub)",
        "neighbors_none": "Nessun vicino trovato con i filtri attuali. Prova ad abbassare VTG o aumentare TMI.",
        "export_btn": "📥 Esporta Intelligence Completa (.txt)",
        "net_map": "🕸️ Mappa di Interazione di Rete",
        "ranking": "📊 Classifica Segnale Hub",
        "desk": "📂 Hub Intelligence Desk:",
        "therap": "### 💊 Terapie",
        "trials": "### 🧪 Trial Clinici",
        "paths": "### 🧬 Pathways",
        "no_odi": "Nessuna terapia trovata in ODI.",
        "no_gci": "Nessun trial trovato in GCI.",
        "no_pmi": "Nessun pathway trovato in PMI.",
        "repo": "📚 Repository di Intelligence MAESTRO",
        "disc_title": "⚠️ DISCLAIMER SCIENTIFICO E LEGALE",
        "disc_body": "<b>MAESTRO Omikron Suite</b> è destinato esclusivamente a uso di ricerca (RUO). Le analisi generate non sostituiscono un parere medico. I dati riflettono lo stato corrente dei database Omikron.",
        "footer": "MAESTRO v20.6 | © 2026 Omikron Orchestra Project | Powered by AXON Intelligence",
        "detected": "RILEVATO",
        "linked": "Collegati",
        "items": "Elementi",
        "details_na": "Dettagli non disponibili.",
    }
}

def t(key: str) -> str:
    return I18N.get(L, I18N["EN"]).get(key, I18N["EN"].get(key, key))
